trigger: none

pool:
  name: projectpool

variables:
  IMAGE_TAG: $(Build.BuildId)
  BRANCH_NAME: main
  ARGOCD_SERVER: http://51.124.55.73
  ARGOCD_APP: microservices

stages:
- stage: Full_Deploy
  displayName: "CI + CD via ArgoCD"
  jobs:
  - job: Deploy
    steps:

    # ✅ Checkout
    - checkout: self
      persistCredentials: true
      clean: true

    # ✅ Update Helm values
    - script: |
        echo "Updating Helm values..."

        sed -i 's|frontend:.*|frontend: gcr.io/google-samples/microservices-demo/frontend:latest|' helm/microservices/values.yaml
        sed -i 's|cart:.*|cart: gcr.io/google-samples/microservices-demo/cartservice:latest|' helm/microservices/values.yaml
        sed -i 's|product:.*|product: gcr.io/google-samples/microservices-demo/productcatalogservice:latest|' helm/microservices/values.yaml
        sed -i 's|checkout:.*|checkout: gcr.io/google-samples/microservices-demo/checkoutservice:latest|' helm/microservices/values.yaml

      displayName: "Update Helm values"

    # ✅ Commit & Push
    - script: |
        git config user.email "shaikhussain752@gmail.com"
        git config user.name "muzzammil-hamdu"

        git add .
        git commit -m "Update images $(IMAGE_TAG)" || echo "No changes"

        git push origin HEAD:$(BRANCH_NAME)
      displayName: "Push to repo"

    # ✅ Install ArgoCD CLI
    - script: |
        echo "Installing ArgoCD CLI..."

        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/
      displayName: "Install ArgoCD CLI"

    # ✅ Login to ArgoCD
    - script: |
        echo "Logging into ArgoCD..."

        argocd login $(ARGOCD_SERVER) \
          --username admin \
          --password ilWEEjcnA-lQEhNc \
          --insecure
      displayName: "ArgoCD Login"

    # ✅ Create App if not exists
    - script: |
        echo "Checking if ArgoCD app exists..."

        if argocd app get $(ARGOCD_APP) > /dev/null 2>&1; then
          echo "App already exists"
        else
          echo "Creating ArgoCD app..."

          argocd app create $(ARGOCD_APP) \
            --repo https://dev.azure.com/<org>/<project>/_git/microservices-demo-app \
            --path helm/microservices \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace default
        fi
      displayName: "Create ArgoCD App (if needed)"

    # ✅ Sync (DEPLOY 🚀)
    - script: |
        echo "Syncing ArgoCD app..."

        argocd app sync $(ARGOCD_APP)
      displayName: "ArgoCD Sync"
