trigger: none

pool:
  name: projectpool

variables:
  IMAGE_TAG: latest

stages:
- stage: Update_Helm
  jobs:
  - job: Update
    steps:

    - checkout: self
      persistCredentials: true

    # Update images to use public images (or ACR later)
    - script: |
        sed -i 's|frontend:.*|frontend: gcr.io/google-samples/microservices-demo/frontend:latest|' helm/microservices/values.yaml
        sed -i 's|cart:.*|cart: gcr.io/google-samples/microservices-demo/cartservice:latest|' helm/microservices/values.yaml
        sed -i 's|product:.*|product: gcr.io/google-samples/microservices-demo/productcatalogservice:latest|' helm/microservices/values.yaml
      displayName: "Update Helm Images"

    # Push back to repo
    - script: |
        git config user.email "shaikhussain752@gmail.com"
        git config user.name "muzzammil-hamdu"

        git add .
        git commit -m "Update image references" || echo "No changes"
        git push
      displayName: "Push changes"
